### ISSUE TITLE
Feature request: RF

### ISSUE THREAD

**Issue by LemADEC** [canitzp/TUMAT#10]
Please add support for RedstoneFlux .

**Comment by canitzp** [comment]
I won't support the old RedstoneFluxAPI even though they updated it, but the Forge internal Energy system is the standard these days. Are there evene mods that don't support forge energy, except IndustrialCraft?

**Comment by LemADEC** [comment]
yes, there is

**Comment by canitzp** [comment]
Which Mods?

**Comment by canitzp** [comment]
If mods support RF but not the forge internal version, than it's there fault and should be done on their end, not mine. I can't find one important mod that has this behaviour

**Comment by LemADEC** [comment]
As a server owner, I can tell you capabilities are bad for TPS, IF is no exception.

**Comment by canitzp** [comment]
1. Which capabilities are bad? I don't provide capabilities, I only used the capabilities provided by Forge or other Mods I have integration for
2. What is IF?
