### ISSUE TITLE
Icon is too transparent

### ISSUE THREAD

**Issue by LemADEC** [canitzp/TUMAT#11]
As of TUMAT-1.12.x-1.12.0.jar, the icon transparency is too high.
Also, I couldn't find a configuration to adjust it.

**Comment by canitzp** [comment]
Could you provide a picture of this? @LemADEC

**Comment by LemADEC** [comment]
Sorry, too many issues in your mod, we're no longer using it.
Simply add an configuration option so we can adjust it.

**Comment by canitzp** [comment]
The icon has no transarency by default, this is why I'm asking

**Comment by LemADEC** [comment]
Yes, the transparency was probably a side effect from my mod.
You clearly have no motivation on addressing issues reported, I'm closing this.

**Comment by canitzp** [comment]
I care about every issue that I can identify as my mistake. If I can't see this, then I'll try to help as much as I can also with bugs at other mods. I couldn't see this issue as mine since icon transparency isn't a thing at all, but I can't help a lot with your mod collection and their errors. I'm sorry about that, but don't tell me that I'm not addressing issues

**Comment by LemADEC** [comment]
The initial problem was that a mod was having an OpenGL leak, causing your HUD to have transparency.
This raised the point that we're missing a transparency setting for your HUD, hence I left the issue after fixing the other mod.
Your initial response on the issues I had opened back in June did discourage me to report the 2 or 3 other issues I've found at that time. I've moved on.

**Comment by canitzp** [comment]
I only work ocasionally on some of my mods, when I think they are stable. Nobody has reported fatal bugs, so I didn't worked on it. No where I go through all my mods and update them, I stuck here. No important bug on my side except this one which isn't either like you said. I'll take a look into preventing a opengl leak from making my HUD transparent. Even if you moved on, it would be nice to report the issues you found
