### ISSUE TITLE
Odd Interaction

### ISSUE THREAD

**Issue by hextrace** [canitzp/TUMAT#4]
Server:  v1.10.2
Forge:  12.18.3.2209

Issue:
Not server/client breaking; however, TUMAT 1.6.0 appears to render the names of the stone blocks from UndergroundBiomesConstructs 0.19-beta.13 as "<stone_type> button":

![image](https://cloud.githubusercontent.com/assets/17187436/22008025/5825adb6-dc45-11e6-85fa-3b2ec2e9f707.png)

Probably not TUMAT at fault as I haven't observed any other random tooltip; however, I figured I'd report it here in the event that there is some tangled code somewhere.  Awesome mod, btw.

EDIT:  Forgot Forge version.  No crash-report to share.

**Comment by canitzp** [comment]
I think this is how Underground Biomes handels their blocks and items internal. What ist the inventory name of the block?

**Comment by hextrace** [comment]
Sorry for the delay.  I also cross-posted the issue with Zeno on UBC's CurseForge page.  Zeno indicated that it is an issue with UBC and not TUMAT.

EDIT:  Thank you for the prompt reply! =)
