### ISSUE TITLE
Error with OreFlowers.

### ISSUE THREAD

**Issue by Claycorp** [canitzp/TUMAT#7]
https://pastebin.com/T5tew3SK

When looking at some Ore flowers you get error instead of what it is.
TUMAT: 1.6.0
MC: 1.10.2
Forge: 12.18.3.2281

**Comment by canitzp** [comment]
Can you help here @draco18s

**Comment by Draco18s** [comment]
I thought I fixed this not that long ago, I remember getting a report. Let me check.

No, apparently not. Huh.

Anyway, it has to do with the fact that TUMATE is trying to get the name for the lower half of a 2-tall flower block by using getMetaForState and passing that value into the Item (which does not support upper and lower halves). TUMATE *should* be using one of getPickBlock or createStackedBlock.

**Comment by canitzp** [comment]
I don't use getPickBlock or createStackedBlock since they aren't always returning the results I want to show @Draco18s

**Comment by Draco18s** [comment]
Eventually you're going to run into trouble, as there is no strictly enforced relationship between block metadata and item metadata. The only place Minecraft itself assumes that is in the custom flat world generator thing, which diesieben7 considers it a bug.

**Comment by canitzp** [comment]
Today I reworked some things at TUMAT and also how I get names from Blocks and Items since I added a Icon render feature and decided to use getPickBlock instead of the metadata thing and I seems like it runs fine, so I keep it

**Comment by Draco18s** [comment]
Cool. :) I'll be fixing my item eventually as well, because it's both easy and avoids an error when other mods do something unexpected.
